### ISSUE TITLE
Invalid weight links

### ISSUE THREAD

**Issue by ai4popugai** [jmisilo/clip-gpt-captioning#83]
Please, update the links for the Large and Small models

**Comment by Swarno-Coder** [comment]
@jmisilo Please update the weight link path for the Large and Small  models
### It's urgent.

**Comment by jmisilo** [comment]
@ai4popugai @Swarno-Coder hello, my drive has been broken. Will try to restore weights and provide them.

**Comment by Swarno-Coder** [comment]
@jmisilo Thanks for replying, getting the model weights means a lot to me.
Hope for the best, because for completing my project these weights are required.

**Comment by jmisilo** [comment]
@ai4popugai @Swarno-Coder I updated URLs. Please check `readme.md`.

Please let me know how your projects will go. Good luck!
